apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-global-conf
data:
  base-url: "{{ .Values.protocol}}://{{ .Values.public_ip}}:{{ .Values.port}}"
  mongo-host: mongo
  elasticsearch-host: elasticsearch
  secret: azerty
  data-fair-api-key: dTo4Z21YOHdjYlY6U3M0akREU1pkRERqOHBnRnFQUVpf
  mails-transport: '{"host": "{{ .Values.protocol}}://{{ .Values.public_ip}}:{{ .Values.port}}/mails"}'

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-conf
data:
  default.conf: |-
    {{ .Files.Get "nginx.conf" | indent 2 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-conf
data:
  prometheus.yml: |-
    scrape_configs:
      - job_name: services-metrics
        scrape_interval: {{ default "120s" .Values.prometheus_scrape_interval }}
        metrics_path: {{ default "/global-metrics" .Values.prometheus_metrics_path }}
        static_configs:
          {{ range .Values.services }}
          {{ if .metrics }}
          - targets: ['{{ .name }}:9090']
            labels:
              service: {{ .name }}
          {{ end }}
          {{ end }}