{{- $release_name := .Release.Name -}}
{{- range .Values.pvcs -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $release_name }}-{{ .name }}-data
spec:
  accessModes:
    {{ range .accessModes -}}
    - {{ . -}}
    {{ else -}}
    - ReadWriteOnce
    {{- end }}
  resources:
    requests:
      storage: {{ default "100Mi" .storage }}
---
{{ end }}