{{- range .Values.apps -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .name }}
  template:
    metadata:
      labels:
        name: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}
          {{- with .volumes }}
          volumeMounts:
            {{ range . }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ default "false" .readOnly }}
            {{ end }}
          {{- end }}
          {{- with .probes }}
          readinessProbe:
            httpGet: 
              path: {{ .httpGet.path }}
              port: {{ .httpGet.port }}
            failureThreshold: {{ .httpGet.failureThreshold }}
            periodSeconds: {{ .httpGet.periodSeconds }}
            initialDelaySeconds: {{ .httpGet.initialDelaySeconds }}
          livenessProbe:
            httpGet: 
              path: {{ .httpGet.path }}
              port: {{ .httpGet.port }}
            failureThreshold: {{ .httpGet.failureThreshold }}
            periodSeconds: {{ .httpGet.periodSeconds }}
            initialDelaySeconds: {{ .httpGet.initialDelaySeconds }}
          startupProbe:
            httpGet: 
              path: {{ .httpGet.path }}
              port: {{ .httpGet.port }}
            failureThreshold: 30
            periodSeconds: 10
          {{- end }}
          {{- with .env }}
          env:
          {{- range . }}
            - name: {{ .name }}
            {{- with .value }}
              value: {{ . | quote }}
            {{- end }}
            {{- with .configMapKeyRef }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .name }}
                  key: {{ .key }}
            {{- end }}
            {{- with .secretKeyRef }}
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}
                  key: {{ .key }}
            {{- end }}
          {{- end }}
          {{- end }}
      {{- with .volumes }}
      
        
      volumes:
      {{- range . }}
        - name: {{ .name }}
        {{- if eq .type "configMap" }}
          configMap:
            name: {{ .name }}
        {{- else if eq .type "persistentVolumeClaim" }}
          persistentVolumeClaim:
            claimName: {{ .name }}
        {{- end }}
      {{- end }}
      {{- end }}
---
{{- end }}