apiVersion: v1
kind: ConfigMap
metadata:
  name: global-conf
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
data:
  base-url: "{{ .Values.proxy.scheme}}://{{ .Values.proxy.public_address }}:{{ .Values.proxy.port}}"
  mongo-host: mongo
  elasticsearch-host: elasticsearch
  secret: azerty
  data-fair-api-key: dTo4Z21YOHdjYlY6U3M0akREU1pkRERqOHBnRnFQUVpf
  mails-transport: '{"host": "{{ .Values.proxy.scheme}}://{{ .Values.proxy.public_address}}:{{ .Values.proxy.port}}/mails"}'

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
data:
  default.conf: |-
    server {
      listen {{ .Values.proxy.port }};
      listen [::]:{{ .Values.proxy.port }};
      server_name {{ .Values.proxy.public_address }};

      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header If-Modified-Since $http_if_modified_since;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_read_timeout 600s;
      client_max_body_size 0;
      proxy_request_buffering off;

      location = / {  
        return 302 /data-fair/;
      }

      {{- range .Values.services }}
      {{- if .inProxy }}
      {{- $Global := . }}
      {{- range .ports }}
      location /{{ .name }} {
        rewrite  ^/{{ .name }}/(.*) /$1 break;
        proxy_pass http://{{ $Global.name }}:{{ .port }}/;
      }
      {{- end }}
      {{- end }}
      {{- end }}
    }
