apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: elasticsearch
  template:
    metadata:
      labels:
        name: elasticsearch
    spec:
      containers:
        - image: ghcr.io/data-fair/elasticsearch:7.17.1
          name: elasticsearch
          ports:
            - containerPort: 9200
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
          env:
            - name: discovery.type
              value: single-node
          volumeMounts:
            - mountPath: /var/lib/elasticsearch/data
              name: elasticsearch-data
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
spec:
  type: NodePort
  selector:
    name: elasticsearch
  ports:
    - name: "tcp"
      port: 9200
      targetPort: 9200
