{{- range .Values.services -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
spec:
  selector:
    name: {{ .name }}
  {{- with .externalName }}
  type: ExternalName
  externalName: {{ . }}
  {{- else }}
  type: {{ default "ClusterIP" .type }}
  ports:
    {{- range .ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ default .port .targetPort }}
      protocol: {{ default "TCP" .protocol }}
      {{- with .nodePort }}
      nodePort: {{ . }}
      {{- end }}
    {{- end }}
    {{- if .metrics }}
    - name: prometheus
      port: 9090
      targetPort: 9090
    {{- end }}
  {{- end }}
---
{{ end }}
